"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production to prevent exposure of sensitive information
DEBUG = False

# ALLOWED_HOSTS should be configured for production
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
]

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files configuration for profile photos
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# HTTPS AND SECURITY SETTINGS
# ============================================================================

# HTTPS Redirect Configuration
# -----------------------------------------------------------------------------
# SECURE_SSL_REDIRECT: Redirects all non-HTTPS requests to HTTPS
# This ensures all traffic to the application is encrypted
# CRITICAL: Only enable in production with valid SSL certificate
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# -----------------------------------------------------------------------------
# SECURE_HSTS_SECONDS: Time (in seconds) browsers should remember to only 
# access the site via HTTPS. Set to 31536000 (1 year) for production.
# This prevents protocol downgrade attacks and cookie hijacking
SECURE_HSTS_SECONDS = 31536000  # 1 year

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Applies HSTS policy to all subdomains
# Ensures all subdomains are also accessed via HTTPS only
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allows site to be included in browsers' HSTS preload list
# Provides protection even on first visit before HSTS header is received
SECURE_HSTS_PRELOAD = True

# Secure Cookie Configuration
# -----------------------------------------------------------------------------
# SESSION_COOKIE_SECURE: Ensures session cookies are only sent over HTTPS
# Prevents session hijacking via man-in-the-middle attacks
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: Ensures CSRF cookies are only sent over HTTPS
# Protects CSRF tokens from being intercepted over insecure connections
CSRF_COOKIE_SECURE = True

# Additional Secure Headers
# -----------------------------------------------------------------------------
# X_FRAME_OPTIONS: Prevents site from being displayed in frames/iframes
# Set to 'DENY' to completely prevent framing (clickjacking protection)
# Alternative: 'SAMEORIGIN' allows framing by same domain only
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents browsers from MIME-sniffing
# Forces browsers to respect declared content-type
# Helps prevent XSS attacks via content-type confusion
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering
# Provides additional protection against reflected XSS attacks
# Modern browsers have this enabled by default, but explicit is better
SECURE_BROWSER_XSS_FILTER = True

# Content Security Policy (CSP)
# -----------------------------------------------------------------------------
# Defines approved sources of content that browsers should load
# Helps prevent XSS, clickjacking, and other code injection attacks
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'",)

# Proxy Configuration (if behind reverse proxy)
# -----------------------------------------------------------------------------
# SECURE_PROXY_SSL_HEADER: Tells Django to trust X-Forwarded-Proto header
# Only enable if behind a trusted proxy (e.g., Nginx, Apache, AWS ELB)
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Development Override
# -----------------------------------------------------------------------------
# NOTE: For local development without SSL certificate, you can temporarily
# disable these settings. NEVER deploy to production with these disabled!
# Uncomment the following lines for local development only:
#
# import sys
# if 'runserver' in sys.argv:
#     SECURE_SSL_REDIRECT = False
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False
#     SECURE_HSTS_SECONDS = 0
